#!/usr/bin/env python3
"""Embed the EiBi shortwave schedule into the firmware image.

    python3 tools/eibi_embed.py --fetch          # download current eibi.txt, embed it
    python3 tools/eibi_embed.py eibi.txt         # embed a file you already have
    python3 tools/eibi_embed.py tools/eibi_seed.txt   # the built-in seed

Writes firmware/ats-mini/ats-mini/EiBiData.h, which the AirTime build compiles
in; on boot the device installs it into LittleFS as schedules.bin using the
STOCK parser (eibiParseLine), so this tool never needs to understand the
binary format — it cannot fall out of step with the firmware's idea of it.

Why embedded at all: this radio's network is its own bare access point with no
route to the internet, by design (PLAN.md §2 — WiFi is a liability to the
clock, not a connection). Stock ats-mini downloads the schedule from
eibispace.de, which on this device can never work. So the schedule travels
inside the image: ~600 KB in a 3 MB app slot that was 55% empty.

What the tool does to the text:
  * keeps only lines the device parser would accept (starts with a digit,
    parseable frequency, 100..30000 kHz — the SI4732's world)
  * truncates each line at column 58: the parser reads exactly 58 columns
    (14 freq + 9 time + 11 days + 24 name) and the rest of eibi.txt's line
    (language, target, remarks) would be dead weight in flash
  * SORTS by frequency. The device's binary search requires it, and the
    device trusts rather than checks — the real eibi.txt happens to be
    sorted, but this makes it an invariant instead of luck.

The dataset version (content hash) is stored alongside, and the device
re-installs only when it changes — so every boot after the first is a
string-compare, not a 600 KB parse.
"""
import argparse
import hashlib
import pathlib
import sys
import urllib.request

EIBI_URL = "http://eibispace.de/dx/eibi.txt"
HEADER = pathlib.Path(__file__).resolve().parent.parent / \
    "firmware" / "ats-mini" / "ats-mini" / "EiBiData.h"

# The columns eibiParseLine() actually reads: sscanf "%14c%9c%11c%24c".
LINE_COLS = 14 + 9 + 11 + 24


def parse_freq(line):
    """The device does (uint16_t)atof(cols 0..13); mirror that exactly."""
    field = line[:14]
    try:
        return int(float(field.strip().split()[0])) if field.strip() else None
    except (ValueError, IndexError):
        return None


def usable(line):
    s = line.strip()
    if not s or not s[0].isdigit():
        return False
    f = parse_freq(line)
    return f is not None and 100 <= f <= 30000


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("source", nargs="?", help="eibi.txt to embed")
    ap.add_argument("--fetch", action="store_true",
                    help="download the current schedule from %s" % EIBI_URL)
    a = ap.parse_args()

    if a.fetch:
        print("fetching %s ..." % EIBI_URL)
        raw = urllib.request.urlopen(EIBI_URL, timeout=60).read()
        text = raw.decode("latin-1")
    elif a.source:
        text = pathlib.Path(a.source).read_text(encoding="latin-1")
    else:
        ap.error("give a source file or --fetch")

    lines = [ln.rstrip()[:LINE_COLS] for ln in text.splitlines() if usable(ln)]
    if not lines:
        sys.exit("no usable schedule lines found — is this really eibi.txt?")

    # The invariant the device's binary search silently relies on.
    lines.sort(key=parse_freq)

    body = ("\n".join(lines) + "\n").encode("latin-1")
    version = hashlib.sha1(body).hexdigest()[:12]

    out = []
    out.append("// Generated by tools/eibi_embed.py — do not edit by hand.")
    out.append("// %d schedule entries, %d bytes, dataset %s."
               % (len(lines), len(body), version))
    out.append("// Regenerate with a current schedule:")
    out.append("//   python3 tools/eibi_embed.py --fetch")
    out.append("#pragma once")
    out.append("#include <stddef.h>")
    out.append("#include <stdint.h>")
    out.append('static const char kEibiDataVersion[] = "%s";' % version)
    out.append("static const size_t kEibiTextLen = %d;" % len(body))
    out.append("static const uint8_t kEibiText[] = {")
    for i in range(0, len(body), 20):
        out.append("  " + ",".join(str(b) for b in body[i:i + 20]) + ",")
    out.append("};")
    HEADER.write_text("\n".join(out) + "\n")

    print("wrote %s" % HEADER)
    print("  %d entries, %d bytes embedded, dataset %s"
          % (len(lines), len(body), version))
    lo, hi = parse_freq(lines[0]), parse_freq(lines[-1])
    print("  frequency span %d..%d kHz" % (lo, hi))


if __name__ == "__main__":
    main()
