#!/usr/bin/env python3
"""Generate the iOS home-screen icon and emit it as a C byte array.

    python3 tools/make_icon.py

Writes firmware/ats-mini/ats-mini/AirTimeIcon.h. iOS wants a real PNG for
apple-touch-icon (SVG and data: URIs are unreliable there), and this device
has no internet to fetch one from — so it ships in the image like everything
else. 180x180 is the size iOS asks for on modern iPhones; it downscales
cleanly for every smaller slot.
"""
import pathlib
from PIL import Image, ImageDraw

S = 180
BG, FACE, HAND, ACCENT = (13, 18, 32), (233, 238, 247), (13, 18, 32), (255, 176, 46)

im = Image.new("RGB", (S * 4, S * 4), BG)   # 4x then downsample = cheap AA
d = ImageDraw.Draw(im)
c, r = S * 2, int(S * 1.42)

d.ellipse([c - r, c - r, c + r, c + r], fill=FACE)

# Ticks at the quarters — the FT8 slot boundaries, which is the joke and also
# the point: this clock's whole job is the quarter minute.
for i in range(12):
    import math
    a = math.radians(i * 30 - 90)
    long_tick = (i % 3 == 0)
    r0 = r * (0.74 if long_tick else 0.84)
    w = int(S * 0.13 if long_tick else S * 0.06)
    d.line([c + r0 * math.cos(a), c + r0 * math.sin(a),
            c + r * 0.93 * math.cos(a), c + r * 0.93 * math.sin(a)],
           fill=ACCENT if long_tick else (150, 158, 175), width=w)

# Hands at 10:09 — the classic watch-advert pose, and it keeps both hands
# clear of the ticks so the shape still reads at 40 px.
import math
for ang, length, width in ((-90 + 304, 0.52, S * 0.17), (-90 + 54, 0.72, S * 0.12)):
    a = math.radians(ang)
    d.line([c, c, c + r * length * math.cos(a), c + r * length * math.sin(a)],
           fill=HAND, width=int(width))
d.ellipse([c - S * 0.13, c - S * 0.13, c + S * 0.13, c + S * 0.13], fill=ACCENT)

im = im.resize((S, S), Image.LANCZOS)
png = pathlib.Path("/tmp/airtime_icon.png")
im.save(png, "PNG", optimize=True)
data = png.read_bytes()

out = pathlib.Path(__file__).resolve().parent.parent / \
    "firmware" / "ats-mini" / "ats-mini" / "AirTimeIcon.h"
lines = ["// Generated by tools/make_icon.py — do not edit by hand.",
         "// %d x %d apple-touch-icon, %d bytes." % (S, S, len(data)),
         "#pragma once", "#include <stddef.h>", "#include <stdint.h>",
         "static const size_t kAirTimeIconLen = %d;" % len(data),
         "static const uint8_t kAirTimeIcon[] = {"]
for i in range(0, len(data), 20):
    lines.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",")
lines.append("};")
out.write_text("\n".join(lines) + "\n")
print("%s: %d bytes" % (out, len(data)))
